# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-13 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(blank=True, max_length=25)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('import_date', models.DateField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
    ]
