# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-14 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_importhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='importhistory',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
