# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-27 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_importhistory_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='POS',
        ),
    ]
